### ISSUE TITLE
AttributeError: 'QwtPlot' object has no attribute 'enableAxis'

### ISSUE THREAD

**Issue by mahdi-ln** [wolfc01/procexp#20]
```
$ procexp
Call to __main__
app created: '<PyQt5.QtWidgets.QApplication object at 0x7f7928aeb6d0>'
Traceback (most recent call last):
  File "/usr/lib/procexp/procexp.py", line 563, in <module>
    prepareUI(g_mainUi)
  File "/usr/lib/procexp/procexp.py", line 315, in prepareUI
    _ = plotobjects.procExpPlot(mainUi.qwtPlotOverallCpuHist, scale, hasGrid=False)
  File "/usr/lib/procexp/plotobjects/__init__.py", line 56, in __init__
    self.__plot__.enableAxis(0, False )
AttributeError: 'QwtPlot' object has no attribute 'enableAxis'
```
OS: Arch linux
Build script used: https://aur.archlinux.org/packages/procexp/

**Comment by mahdi-ln** [comment]
Ok I had to add python2.7 in command line:
```
$ /usr/bin/python2.7 '/home/m/Downloads/c/procexp-master/procexp.py' 
```

**Comment by mahdi-ln** [comment]
https://gitpay.me/#/task/600
